# docker-compose -f webserver/docker-compose.yml up -d
networks:
    s84account:
        external: true
services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./cert:/etc/nginx/cert:ro
            - ./dist:/dist:ro
        networks:
            s84account:
                ipv4_address: 172.18.3.1
